/*
 *  Localizable.strings.h
 *  ST
 *
 *
 */

#define LOC(locKey) (NSLocalizedString(locKey, nil))


#define LANG @"LANG"
#define UNSPEC @"UNSPEC"

#define CPTPC_PHONE @"CPTPC_PHONE"
#define CPTPC_MOBILE @"CPTPC_MOBILE"

#define PROBLEM @"PROBLEM"
#define ERR_SMTH_WENT_WRONG @"ERR_SMTH_WENT_WRONG"
#define ERR_NO_EMAIL @"ERR_NO_EMAIL"
#define ERR_NO_INTERNET_CONNECTION	@"ERR_NO_INTERNET_CONNECTION"
#define ERR_UNSUCCESS_LOGIN @"ERR_UNSUCCESS_LOGIN"

// Recurring text

#define CANCEL @"CANCEL"
#define CONTINUE @"CONTINUE"
#define CLOSE @"CLOSE"
#define UNSPEC @"UNSPEC"

#define OKAY @"OKAY"
#define SKIP @"SKIP"
#define EDIT @"EDIT"
#define DONE @"DONE"
#define ERROR @"ERROR"

#define NOPE @"NO"
#define YEP @"YES"

// AppDelegate
#define AD_UPDATE @"AD_UPDATE"

// SideMenuViewController
#define SMVC_MARKETS @"SMVC_MARKETS"
#define SMVC_SETTINGS @"SMVC_SETTINGS"
#define SMVC_ACCOUNT @"SMVC_ACCOUNT"
#define SMVC_NOTIFICATIONS @"SMVC_NOTIFICATIONS"
#define SMVC_RECENTS @"SMVC_RECENTS"

// ContentListViewController
#define CLVC_MENU @"CLVC_MENU"
#define CLVC_ORDERING @"CLVC_ORDERING"

// ContentViewController
#define CVC_TITLE @"CVC_TITLE"

// NotificationsViewController
#define NVC_TITLE @"NVC_TITLE"
#define NVC_NOTIFY_SECTION @"NVC_NOTIFY_SECTION"
#define NVC_NEW_CONTENT @"NVC_NEW_CONTENT"

//SignInViewController
#define SIVC_TITLE @"SIVC_TITLE"
#define SIVC_SIGNUP @"SIVC_SIGNUP"
#define SIVC_LOGIN @"SIVC_LOGIN"
#define SIVC_USERNAME @"SIVC_USERNAME"
#define SIVC_PASSWORD @"SIVC_PASSWORD"

//AccountViewController
#define AVC_TITLE @"AVC_TITLE"
#define AVC_LOGOUT @"AVC_LOGOUT"

//TabBarController
#define TBC_HOME @"TBC_HOME"
#define TBC_PRODUCTS @"TBC_PRODUCTS"
#define TBC_QUOTE @"TBC_QUOTE"
#define TBC_ORDER @"TBC_ORDER"
#define TBC_SEARCH @"TBC_SEARCH"
#define TBC_SETTINGS @"TBC_SETTINGS"

//SettingViewController
#define SVC_CELL_TITLE_CONTACT @"SVC_CELL_TITLE_CONTACT"
#define SVC_CELL_TITLE_COMPANY @"SVC_CELL_TITLE_COMPANY"
#define SVC_CELL_TITLE_SHIPING_ADDRESS @"SVC_CELL_TITLE_SHIPING_ADDRESS"
#define SVC_CELL_TITLE_ACCOUNT_NUMBER @"SVC_CELL_TITLE_ACCOUNT_NUMBER"
#define SVC_CELL_TITLE_PHONE @"SVC_CELL_TITLE_PHONE"
#define SVC_CELL_TITLE_EMAIL @"SVC_CELL_TITLE_EMAIL"
#define SVC_PUSH_LABEL @"SVC_PUSH_LABEL"
#define SVC_EMAIL_CONFIRMATION_LABEL @"SVC_EMAIL_CONFIRMATION_LABEL"

//Search View
#define SV_PROMT @"SV_PROMT"
#define SV_PLACEHOLDER @"SV_PLACEHOLDER"

//Detail View
#define DV_PRODUCT_TITLE @"DV_PRODUCT_TITLE"
#define DV_REFERENCE_NUMBER @"DV_REFERENCE_NUMBER"
#define DV_ALLOY @"DV_ALLOY"
#define DV_TEMPER @"DV_TEMPER"
#define DV_WIDTH @"DV_WIDTH"
#define DV_FINISH @"DV_FINISH"
#define DV_MAX_ID @"DV_MAX_ID"
#define DV_MAX_OD @"DV_MAX_OD"
#define DV_REQUESTED_YIELD @"DV_REQUESTED_YIELD"
#define DV_FAB_PRICE @"DV_FAB_PRICE"
#define DV_FEREIGHT_COST @"DV_FEREIGHT_COST"
#define DV_TOTAL_PRICE @"DV_TOTAL_PRICE"
#define DV_ORDER_TITLE @"DV_ORDER_TITLE"
#define DV_QUOTE_TITLE @"DV_QUOTE_TITLE"
#define DV_EST_DATE @"DV_EST_DATE"
#define DV_REQ_DATE @"DV_REQ_DATE"
#define DV_MESSAGE_ERROR_CREATE_QUOTE @"DV_MESSAGE_ERROR_CREATE_QUOTE"
#define DV_MESSAGE_ORDER_CONFIRMATION_TITLE @"DV_MESSAGE_ORDER_CONFIRMATION_TITLE"
#define DV_MESSAGE_ORDER_CONFIRMATION_TEXT @"DV_MESSAGE_ORDER_CONFIRMATION_TEXT"
#define DV_MESSAGE_ERROR_CREATE_ORDER @"DV_MESSAGE_ERROR_CREATE_ORDER"
#define DV_BUTTON_RECREATE_ORDER @"DV_BUTTON_RECREATE_ORDER"
#define DV_BUTTON_SUBMIT_ORDER @"DV_BUTTON_SUBMIT_ORDER"

//New Quote View Contoller
#define NQV_PLACEHOLDER_PRODUCT @"NQV_PLACEHOLDER_PRODUCT"
#define NQV_PLACEHOLDER_ACTIVE_USER @"NQV_PLACEHOLDER_ACTIVE_USER"
#define NQV_PLACEHOLDER_BUSINESS_LOGIC_SCRIPTS @"NQV_PLACEHOLDER_BUSINESS_LOGIC_SCRIPTS"
#define NQV_PLACEHOLDER_SCHEDULED_BUSINESS_LOGIC @"NQV_PLACEHOLDER_SCHEDULED_BUSINESS_LOGIC"
#define NQV_PLACEHOLDER_COLLABORATORS @"NQV_PLACEHOLDER_COLLABORATORS"
#define NQV_PLACEHOLDER_BACKEND_ENVIROMENTS @"NQV_PLACEHOLDER_BACKEND_ENVIROMENTS"
#define NQV_PLACEHOLDER_DATA_STOREGE @"NQV_PLACEHOLDER_DATA_STOREGE"
#define NQV_PLACEHOLDER_BUSINESS_LOGIC_EXECUTION_TIME_LIMIT @"NQV_PLACEHOLDER_BUSINESS_LOGIC_EXECUTION_TIME_LIMIT"
#define NQV_PLACEHOLDER_START_SUBSCRIPTION_DATE @"NQV_PLACEHOLDER_START_SUBSCRIPTION_DATE"
#define NQV_BUTTON_SUBMIT @"NQV_BUTTON_SUBMIT"
#define NQV_TITLE @"NQV_TITLE"

//Main Table View Header
#define MTVH_TITLE_ORDER @"MTVH_TITLE_ORDER"
#define MTVH_DATE_ORDER @"MTVH_DATE_ORDER"
#define MTVH_NO_ORDER @"MTVH_NO_ORDER"
#define MTVH_START_SUBSCRIPTION_DATE @"MTVH_START_SUBSCRIPTION_DATE"
#define MTVH_STATUS_ORDER @"MTVH_STATUS_ORDER"
#define MTVH_MORE_ORDER @"MTVH_MORE_ORDER"
#define MTVH_TITLE_QUOTE @"MTVH_TITLE_QUOTE"
#define MTVH_DATE_QUOTE @"MTVH_DATE_QUOTE"
#define MTVH_NO_QUOTE @"MTVH_NO_QUOTE"
#define MTVH_PRICE_QUOTE @"MTVH_PRICE_QUOTE"
#define MTVH_MORE_QUOTE @"MTVH_MORE_QUOTE"

//Home and Search View Controller
#define HaSVC_LEBEL_COUNT_RESULT @"HaSVC_LEBEL_COUNT_RESULT"

//Quote Home View Controller
#define QHVC_CELL_NO_QUOTE @"QHVC_CELL_NO_QUOTE"
#define QHVC_REFRESH_CONTROL_TITLE @"QHVC_REFRESH_CONTROL_TITLE"
#define QHVC_TITLE @"QHVC_TITLE"

//Order Home View Controller
#define OHVC_CELL_NO_ORDER @"OHVC_CELL_NO_ORDER"
#define OHVC_REFRESH_CONTROL_TITLE @"OHVC_REFRESH_CONTROL_TITLE"
#define OHVC_TITLE @"OHVC_TITLE"

//Product Home View Controller
#define PHVC_CELL_NO_PRODUCTS @"PHVC_CELL_NO_PRODUCTS"
#define PHVC_REFRESH_CONTROL_TITLE @"PHVC_REFRESH_CONTROL_TITLE"
#define PHVC_TITLE @"PHVC_TITLE"
#define PHVC_BUTTON_NEW_QUOTE @"PHVC_BUTTON_NEW_QUOTE"





