/*
 *  Localizable.strings.h
 *  ST
 *
 *
 *
 * Copyright (c) 2014 Kinvey Inc. *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at *
 * http://www.apache.org/licenses/LICENSE-2.0 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License. *
 */
#define LOC(locKey) (NSLocalizedString(locKey, nil))


#define LANG @"LANG"
#define UNSPEC @"UNSPEC"

#define ERR_SMTH_WENT_WRONG @"ERR_SMTH_WENT_WRONG"

// Recurring text

#define CANCEL @"CANCEL"
#define CLOSE @"CLOSE"

#define OKAY @"OKAY"
#define EDIT @"EDIT"
#define DONE @"DONE"
#define ERROR @"ERROR"

//SignInViewController
#define SIVC_TITLE @"SIVC_TITLE"
#define SIVC_SIGNUP @"SIVC_SIGNUP"
#define SIVC_LOGIN @"SIVC_LOGIN"
#define SIVC_USERNAME @"SIVC_USERNAME"
#define SIVC_PASSWORD @"SIVC_PASSWORD"

//TabBarController
#define TBC_PRODUCTS @"TBC_PRODUCTS"
#define TBC_QUOTE @"TBC_QUOTE"
#define TBC_ORDER @"TBC_ORDER"
#define TBC_NEW_QUOTES @"TBC_NEW_QUOTES"
#define TBC_ABOUT @"TBC_ABOUT"
#define TBC_SETTINGS @"TBC_SETTINGS"

//SettingViewController
#define SVC_CELL_TITLE_CONTACT @"SVC_CELL_TITLE_CONTACT"
#define SVC_CELL_TITLE_COMPANY @"SVC_CELL_TITLE_COMPANY"
#define SVC_CELL_TITLE_ACCOUNT_NUMBER @"SVC_CELL_TITLE_ACCOUNT_NUMBER"
#define SVC_CELL_TITLE_PHONE @"SVC_CELL_TITLE_PHONE"
#define SVC_CELL_TITLE_EMAIL @"SVC_CELL_TITLE_EMAIL"
#define SVC_PUSH_LABEL @"SVC_PUSH_LABEL"
#define SVC_EMAIL_CONFIRMATION_LABEL @"SVC_EMAIL_CONFIRMATION_LABEL"
#define SVC_BUTTON_LOGOUT @"SVC_BUTTON_LOGOUT"


//Detail View
#define DV_PRODUCT_TITLE @"DV_PRODUCT_TITLE"
#define DV_REFERENCE_NUMBER @"DV_REFERENCE_NUMBER"
#define DV_ACTIVE_USER @"DV_ACTIVE_USER"
#define DV_BUSINESS_LOGIC_SCRIPTS @"DV_BUSINESS_LOGIC_SCRIPTS"
#define DV_SCHEDULED_BUSINESS_LOGIC @"DV_SCHEDULED_BUSINESS_LOGIC"
#define DV_COLLABORATORS @"DV_COLLABORATORS"
#define DV_BACKEND_ENVIRONMENTS @"DV_BACKEND_ENVIRONMENTS"
#define DV_DATA_STORAGE @"DV_DATA_STORAGE"
#define DV_BUSINESS_EXECUTION_TIME_LIMIT @"DV_BUSINESS_EXECUTION_TIME_LIMIT"
#define DV_START_SUBSCRIPTION_DATE @"DV_START_SUBSCRIPTION_DATE"
#define DV_TOTAL_COST @"DV_TOTAL_COST"
#define DV_ORDER_TITLE @"DV_ORDER_TITLE"
#define DV_QUOTE_TITLE @"DV_QUOTE_TITLE"
#define DV_MESSAGE_ERROR_CREATE_QUOTE @"DV_MESSAGE_ERROR_CREATE_QUOTE"
#define DV_MESSAGE_ORDER_CONFIRMATION_TITLE @"DV_MESSAGE_ORDER_CONFIRMATION_TITLE"
#define DV_MESSAGE_ORDER_CONFIRMATION_TEXT @"DV_MESSAGE_ORDER_CONFIRMATION_TEXT"
#define DV_MESSAGE_ERROR_CREATE_ORDER @"DV_MESSAGE_ERROR_CREATE_ORDER"
#define DV_BUTTON_RECREATE_ORDER @"DV_BUTTON_RECREATE_ORDER"
#define DV_BUTTON_SUBMIT_ORDER @"DV_BUTTON_SUBMIT_ORDER"

//New Quote View Contoller
#define NQV_PLACEHOLDER_PRODUCT @"NQV_PLACEHOLDER_PRODUCT"
#define NQV_PLACEHOLDER_ACTIVE_USER @"NQV_PLACEHOLDER_ACTIVE_USER"
#define NQV_PLACEHOLDER_BUSINESS_LOGIC_SCRIPTS @"NQV_PLACEHOLDER_BUSINESS_LOGIC_SCRIPTS"
#define NQV_PLACEHOLDER_SCHEDULED_BUSINESS_LOGIC @"NQV_PLACEHOLDER_SCHEDULED_BUSINESS_LOGIC"
#define NQV_PLACEHOLDER_COLLABORATORS @"NQV_PLACEHOLDER_COLLABORATORS"
#define NQV_PLACEHOLDER_BACKEND_ENVIROMENTS @"NQV_PLACEHOLDER_BACKEND_ENVIROMENTS"
#define NQV_PLACEHOLDER_DATA_STOREGE @"NQV_PLACEHOLDER_DATA_STOREGE"
#define NQV_PLACEHOLDER_BUSINESS_LOGIC_EXECUTION_TIME_LIMIT @"NQV_PLACEHOLDER_BUSINESS_LOGIC_EXECUTION_TIME_LIMIT"
#define NQV_PLACEHOLDER_START_SUBSCRIPTION_DATE @"NQV_PLACEHOLDER_START_SUBSCRIPTION_DATE"
#define NQV_BUTTON_SUBMIT @"NQV_BUTTON_SUBMIT"
#define NQV_TITLE @"NQV_TITLE"
#define NQV_TOP_BAR_TITLE @"NQV_TOP_BAR_TITLE"

//Main Table View Header
#define MTVH_TITLE_ORDER @"MTVH_TITLE_ORDER"
#define MTVH_DATE_ORDER @"MTVH_DATE_ORDER"
#define MTVH_NO_ORDER @"MTVH_NO_ORDER"
#define MTVH_START_SUBSCRIPTION_DATE @"MTVH_START_SUBSCRIPTION_DATE"
#define MTVH_STATUS_ORDER @"MTVH_STATUS_ORDER"
#define MTVH_MORE_ORDER @"MTVH_MORE_ORDER"
#define MTVH_TITLE_QUOTE @"MTVH_TITLE_QUOTE"
#define MTVH_DATE_QUOTE @"MTVH_DATE_QUOTE"
#define MTVH_NO_QUOTE @"MTVH_NO_QUOTE"
#define MTVH_PRICE_QUOTE @"MTVH_PRICE_QUOTE"
#define MTVH_MORE_QUOTE @"MTVH_MORE_QUOTE"

//Home and Search View Controller
#define HaSVC_LEBEL_COUNT_RESULT @"HaSVC_LEBEL_COUNT_RESULT"

//Quote Home View Controller
#define QHVC_CELL_NO_QUOTE @"QHVC_CELL_NO_QUOTE"
#define QHVC_REFRESH_CONTROL_TITLE @"QHVC_REFRESH_CONTROL_TITLE"
#define QHVC_TITLE @"QHVC_TITLE"

//Order Home View Controller
#define OHVC_CELL_NO_ORDER @"OHVC_CELL_NO_ORDER"
#define OHVC_REFRESH_CONTROL_TITLE @"OHVC_REFRESH_CONTROL_TITLE"
#define OHVC_TITLE @"OHVC_TITLE"

//Product Home View Controller
#define PHVC_CELL_NO_PRODUCTS @"PHVC_CELL_NO_PRODUCTS"
#define PHVC_REFRESH_CONTROL_TITLE @"PHVC_REFRESH_CONTROL_TITLE"
#define PHVC_TITLE @"PHVC_TITLE"
#define PHVC_BUTTON_NEW_QUOTE @"PHVC_BUTTON_NEW_QUOTE"

//About View Controller
#define AVC_TITLE @"AVC_TITLE"



